#
# OpenAPI 3.x Schema for the 'Action' Data Model
#
# This file defines the schema for the 'Action' object, which represents a
# reified event as the most granular, atomic unit of change
# in the SAT-Graph.
#
# An Action is a first-class entity that models a single, auditable causal
# link, connecting a specific clause of an authorizing law to the specific
# change it enacts.
#
type: object
description: >
  Represents a reified event (e.g., an amendment, a revocation).
  It is a first-class entity that models a single, auditable causal link,
  connecting the source of a command to its precise effects on the version
  history of an Item.
required:
  - id
  - type
  - date
  - source_version_id
  - produces_version_id
properties:
  id:
    $ref: '../core/ID.yaml'
    description: "A unique identifier for this specific action."
    example: "urn:lex:br:federal:emenda.constitucional:2000-02-14;26@2000-02-14!art1_cpt_alt1_art6_cpt"
  type:
    type: string
    description: >-
      The type of action. The enumerated values represent a baseline
      set; a concrete implementation may extend this list.
    enum:
      - "Amendment"
      - "Revocation"
      - "Creation"
      - "Repeal"
    example: "Amendment"
  date:
    type: string
    format: date-time
    description: "The effective date and time of the action, in UTC."
    example: "2000-02-14T00:00:00Z"
  source_version_id:
    $ref: '../core/ID.yaml'
    description: >-
      The ID of the specific 'Version' of the legal text that **authorizes**
      or **commands** this single change. This is the source of the causal link.
    example: "urn:lex:br:federal:emenda.constitucional:2000-02-14;26@2000-02-14!art1_cpt_alt1_art6_cpt"
  terminates_version_id:
    $ref: '../core/ID.yaml'
    nullable: true
    description: >-
      The ID of the specific 'Version' whose validity is **terminated** by this
      action. This is optional and will be null for original enactments (Creations).
    example: "urn:lex:br:federal:constituicao:1988-10-05;1988@1988-10-05!art6_cpt"
  produces_version_id:
    $ref: '../core/ID.yaml'
    description: >-
      The ID of the specific 'Version' that is **created** by this action.
    example: "urn:lex:br:federal:constituicao:1988-10-05;1988@2000-02-14!art6_cpt"
  metadata:
    $ref: '../core/JSON.yaml'
    nullable: true
    description: >-
      A flexible field for any valid JSON data providing more context about the
      action, such as its source of the assertion.
